set dotenv-load

EFS_ID := env_var("EFS_ID")  # For example: 'fs-0ae474bb0403fc7c6'
SLURM_VERSION := env_var("SLURM_VERSION")
#AD_DOMAIN := env_var("AD_DOMAIN")
#AD_PASSWD := env_var("AD_PASSWD")


# -----------------------------------------------------------------------------
# Build RSW
# -----------------------------------------------------------------------------

# Install RStudio workbench and all of the dependencies
build-slurm-head-nodes: 
    #!/bin/env bash
    # Basic setup
    just install-efs-utils
    just mount-efs 
    just slurm-prereqs
    if [ ! -d /opt/slurm/bin ]; then 
        just slurm-compile-and-install
    fi 
    just slurm-logs-prepare
    just slurm-copy-config
    just slurm-start-daemons

slurm-start-daemons:
    #!/bin/env bash
    sudo /opt/slurm/sbin/slurmdbd 
    sudo /opt/slurm/sbin/slurmctld

slurm-copy-config:
    #!/bin/env bash
    sudo cp slurmdbd.conf /opt/slurm/etc
    sudo chmod 0600 /opt/slurm/etc/slurmdbd.conf
    sudo chown slurm /opt/slurm/etc/slurmdbd.conf
    sudo cp slurm.conf /opt/slurm/etc 

munge-setup: 
    #!/bin/env bash
    #add munge user
    sudo groupadd -r --gid=105 munge
    sudo useradd -r -s /bin/bash -g munge --uid=105 munge
    #add slurm users
    sudo groupadd -r --gid=995 slurm
    sudo useradd -r -g slurm --uid=995 slurm 
    sudo apt-get install -y libmunge-dev libmunge2 munge

munge-config:
    #!/bin/env bash
    #create key
    sudo dd if=/dev/random bs=1 count=1024 of=/etc/munge/munge.key
    #add permissions
    sudo chown munge:munge /etc/munge/munge.key
    sudo chmod 400 /etc/munge/munge.key
    sudo systemctl restart munge

slurm-logs-prepare:
    #!/bin/env bash
    sudo mkdir -p /var/spool/slurm
    sudo chown slurm:slurm /var/spool/slurm
    sudo chmod 755 /var/spool/slurm
    sudo mkdir -p /var/spool/slurm/slurmctld
    sudo chown slurm:slurm /var/spool/slurm/slurmctld
    sudo chmod 755 /var/spool/slurm/slurmctld
    sudo mkdir -p /var/spool/slurm/cluster_state
    sudo chown slurm:slurm /var/spool/slurm/cluster_state
    sudo touch /var/log/slurmctld.log
    sudo chown slurm:slurm /var/log/slurmctld.log
    sudo touch /var/log/slurm_jobacct.log /var/log/slurm_jobcomp.log
    sudo chown slurm: /var/log/slurm_jobacct.log /var/log/slurm_jobcomp.log
    sudo mkdir -p /opt/slurm/etc
    sudo mkdir -p /var/{lib,log,run}/slurm
    sudo chown slurm:slurm /var/{lib,log,run}/slurm

slurm-prereqs:
    just munge-setup
    just munge-config
    just slurm-logs-prepare
    just slurm-osdeps

slurm-osdeps:
    #!/bin/env bash
    #install os dependencies
    sudo apt-get update 
    sudo apt-get -y install \
       wget \
       bzip2 \
       perl \
       gcc-9 \
       g++-9 \
       gcc \
       g++ \
       git \
       gnupg \
       make \
       libcgroup-dev \
       python-is-python3 \
       python3.8-dev \
       python3-pip \
       cython3 \
       mariadb-client \
       libmariadbd-dev \
       psmisc \
       bash-completion \
       vim \
       python3-nose

slurm-compile-and-install:
    #!/bin/env bash
    tmpdir=`mktemp -d` 
    pushd $tmpdir
    git clone --depth 1 -b slurm-`echo {{SLURM_VERSION}} | sed 's/\./-/g'` https://github.com/SchedMD/slurm.git
    pushd slurm
    ./configure --enable-debug --prefix=/opt/slurm --sysconfdir=/opt/slurm/etc \
        --with-mysql_config=/usr/bin
    make -j $(( 2*`nproc` ))
    sudo make install 
    popd
    sudo rm -rf $tmpdir

slurm-config:
    #!/bin/env
    echo -e "CgroupAutomount=yes\nConstrainCores=yes\nConstrainRAMSpace=yes\nConstrainDevices=yes" | sudo tee -a /opt/slurm/etc/cgroup.conf


install-efs-utils:
    #!/bin/env bash
    export DEBIAN_FRONTEND=noninteractive                   
    set -euxo pipefail
    if ! [ -f /sbin/mount.efs ]; then
        sudo -E apt-get -y install binutils
        tmpdir=`mktemp -d`
        cd $tmpdir 
        git clone https://github.com/aws/efs-utils
        cd efs-utils
        ./build-deb.sh
        sudo -E apt-get -y install ./build/amazon-efs-utils*deb
        cd 
        rm -rf $tmpdir
    fi


mount-efs:
    #!/bin/env bash
    df | grep efs$
    if [ $? -ne 0 ]; then 
        sudo mkdir -p /efs;
        sudo mount -t efs -o tls {{EFS_ID}}:/ /efs;
        just set-efs-conf
    fi

set-efs-conf:
    #!/bin/bash
    sudo bash -c 'cat <<EOF >> /etc/fstab
    # mount efs
    {{EFS_ID}}:/ /efs efs defaults,_netdev 0 0
    EOF'
